### ISSUE TITLE
We need a frontend

### ISSUE THREAD

**Issue by cnbeining** [cnbeining/autotimecode#1]
Would be great to have a frontend to call RESTful APIs.

**Comment by onpaik** [comment]
Which type of programming language do you need?

**Comment by cnbeining** [comment]
Does not really matter - I won't pretend that I know anything about Frontend tool chain and would be more than happy to let the pros to decide for the project.

**Comment by langtube** [comment]
请问怎么加入？
我有一些前端开发经验，包括react vue electron等

**Comment by cnbeining** [comment]
1）如果想直接在这个project里加入 可以开个目录 加Dockerfile；

2）如果觉得这样麻烦，欢迎push到自己的repo，在这里comment：我在readme里加入链接，像youtube-dl和youtubedl-dl-gui的关系那样。

**Comment by cnbeining** [comment]
Closed - thanks for the help!

**Comment by langtoo** [comment]
主要是没有api文档。
为什么关闭了issue？

**Comment by cnbeining** [comment]
API文档：https://documenter.getpostman.com/view/2034007/SVmtxJzc?version=latest

欢迎PR。

**Comment by langtoo** [comment]
貌似有个前端项目 autotimecode_fe。
这个是什么情况？

**Comment by cnbeining** [comment]
有大佬送了个前端 嗯。

**Comment by langtoo** [comment]
是可以用的吗？为什么要重新开始弄一个？
